apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: lt-human-approval-test
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: stage1_getsapproval
      jobs:
        - job1
    - name: stage2_needsapproval
      jobs:
        - job
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job:
    needs:
      - job1
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
