apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-workflow-2-gitleaks

on:
  workflow_dispatch:
jobs:
  scan-and-evaluate:
    outputs:
      policy-subject: ${{ steps.build-input.outputs.policy-input }}
    steps:
      - name: Checkout source code
        uses: cloudbees-io/checkout@v1

      - name: Run Gitleaks
        id: gitleaks
        uses: cloudbees-io/gitleaks-plugin
        continue-on-error: true

      - name: Print Gitleaks outputs
        uses: docker://alpine:latest
        run: |
          echo "=== Gitleaks Scan Results ==="
          echo "Critical:       ${{ steps.gitleaks.outputs.critical-count }}"
          echo "Very High:      ${{ steps.gitleaks.outputs.very-high-count }}"
          echo "High:           ${{ steps.gitleaks.outputs.high-count }}"
          echo "Medium:         ${{ steps.gitleaks.outputs.medium-count }}"
          echo "Low:            ${{ steps.gitleaks.outputs.low-count }}"
          echo "Policy subject: ${{ steps.gitleaks.outputs.policy-subject }}"


      - name: Assemble policy input
        id: build-input
        uses: docker://alpine:latest
        run: |
          printf '[%s,%s]' \
            '${{ steps.gitleaks.outputs.policy-subject }}' \
            | tee /tmp/policy-input.json
          cp /tmp/policy-input.json "$CLOUDBEES_OUTPUTS/policy-input"
          echo ""
          echo "=== Combined policy input ==="
          cat /tmp/policy-input.json
